#!/bin/bash
#Script de automatizacao de testes

echo "Digite o numero do teste final: "
read teste
num=1

while [ $num -le $teste ]
do
    echo "Teste $num"
    ./runCompiler.sh testes/$num.c
    mv sint_out.c semantico
    ./semantico/semantico.bin > testing.txt
    
    diff -s testing.txt testes/saida_ass/$num.ass

    (( num++ ))
done
